-- dict_cn_misc.lua
-- Chinese (Simplified) → English word/term substitution table
-- Ported from TranslateCN by Gangasrotogati
-- Format: dict_cn_misc["<CN term>"] = "<EN translation>"

dict_cn_misc = {
    -- Classes
    ["术士"]       = "Warlock",
    ["战士"]       = "Warrior",
    ["猎人"]       = "Hunter",
    ["法师"]       = "Mage",
    ["牧师"]       = "Priest",
    ["德鲁伊"]     = "Druid",
    ["圣骑士"]     = "Paladin",
    ["萨满祭司"]   = "Shaman",
    ["盗贼"]       = "Rogue",
    ["QS"]         = "Paladin",
    ["XD"]         = "Druid",
    ["LR"]         = "Hunter",
    ["FS"]         = "Mage",
    ["DZ"]         = "Rogue",
    ["SM"]         = "Shaman",
    ["SS"]         = "Warlock",
    ["ZS"]         = "Warrior",
    ["MS"]         = "Priest",
    -- Dungeons
    ["NY"]         = "RFC",
    ["AH"]         = "WC",
    ["YY"]         = "SFK",
    ["MD"]         = "Graveyard",
    ["XS"]         = "SM",
    ["ZUL"]        = "ZF",
    ["怒焰"]       = "RFC",
    ["怒焰裂谷"]   = "RFC",
    ["哀嚎洞穴"]   = "WC",
    ["死亡矿坑"]   = "DM",
    ["影牙城堡"]   = "SFK",
    ["黑暗深渊"]   = "BFD",
    ["暴风监狱"]   = "STOCKADES",
    ["剃刀沼泽"]   = "RFK",
    ["诺莫瑞根"]   = "GNOMER",
    ["剃刀高地"]   = "RFD",
    ["血色修道院"] = "SM",
    ["血色"]       = "SM",
    ["教堂"]       = "Cathedral",
    ["图书馆"]     = "Library",
    ["墓地"]       = "Graveyard",
    ["武器库"]     = "Armory",
    ["奥达曼"]     = "ULDAMAN",
    ["祖尔法拉克"] = "ZF",
    ["玛拉顿"]     = "MARAUDON",
    ["塔哈克神庙"] = "ST",
    ["黑石深渊"]   = "BRD",
    ["本通灵学院"] = "SCHOLO",
    ["斯坦索姆"]   = "STRAT",
    ["STSM"]       = "STRAT",
    ["速刷"]       = "speed clear",
    ["速刷队"]     = "speed clear team",
    ["MT"]         = "main tank",
    ["黑石塔下"]   = "LBRS",
    ["黑石塔上"]   = "UBRS",
    ["厄运之槌"]   = "DM",
    -- Roles
    ["坦克"]       = "tank",
    ["治疗"]       = "healer",
    ["奶妈"]       = "healer",
    ["摔绊"]       = "melee",
    ["奶骑"]       = "holy paladin",
    ["鸟德"]       = "boomkin druid",
    ["奶德"]       = "resto druid",
    -- LFG common
    ["招募"]       = "recruiting",
    ["组队"]       = "group up",
    ["开团"]       = "raid forming",
    ["缺人"]       = "need more",
    ["满了"]       = "full",
    ["来"]         = "join",
    ["打"]         = "run",
    ["收"]         = "taking",
    ["需要"]       = "need",
    -- Reactions / chat
    ["谢谢"]       = "thanks",
    ["好的"]       = "okay",
    ["好"]         = "okay",
    ["不"]         = "no",
    ["是"]         = "yes",
    ["哈哈"]       = "haha",
    ["666"]        = "nice",
    -- Guild
    ["公会"]       = "guild",
    ["欢迎"]       = "welcome",
    -- Economy
    ["金"]         = "gold",
    ["G"]          = "gold",
    -- Time
    ["晚上"]       = "tonight",
    ["早上"]       = "morning",
    ["下午"]       = "afternoon",
    -- Misc WoW
    ["任务"]       = "quest",
    ["副本"]       = "dungeon",
    ["团队"]       = "raid",
    ["装备"]       = "gear",
    ["升级"]       = "level up",
    ["复活"]       = "rez",
    ["死了"]       = "dead",
    ["跑路"]       = "run away",
    ["加血"]       = "heal me",
    ["蓝"]         = "mana",
    ["血"]         = "health",
    ["boss"]       = "boss",
    ["BOSS"]       = "boss",

    -- Additional class abbreviations / slang
    ["骑士"]       = "Paladin",
    ["德"]         = "Druid",
    ["萨满"]       = "Shaman",
    ["牧"]         = "Priest",
    ["法"]         = "Mage",
    ["猎"]         = "Hunter",
    ["战"]         = "Warrior",
    ["贼"]         = "Rogue",
    ["术"]         = "Warlock",
    ["奶"]         = "healer",

    -- Additional dungeon names / abbreviations
    ["ZG"]         = "ZG",
    ["MC"]         = "MC",
    ["BWL"]        = "BWL",
    ["AQ40"]       = "AQ40",
    ["AQ20"]       = "AQ20",
    ["Naxx"]       = "Naxx",
    ["熔火之心"]   = "MC",
    ["黑翼之巢"]   = "BWL",
    ["安其拉圣地"] = "AQ40",
    ["祖尔格拉布"] = "ZG",
    ["纳克萨玛斯"] = "Naxx",
    ["奥达曼"]     = "Uldaman",
    ["厄运之槌"]   = "Dire Maul",

    -- Roles / spec slang
    ["DPS"]        = "DPS",
    ["输出"]       = "DPS",
    ["远程"]       = "ranged",
    ["近战"]       = "melee",
    ["主坦"]       = "main tank",
    ["副坦"]       = "off-tank",
    ["减员"]       = "crowd control",
    ["CC"]         = "CC",
    ["AOE"]        = "AOE",

    -- Combat / mechanics
    ["仇恨"]       = "threat",
    ["拉怪"]       = "pull",
    ["拉"]         = "pull",
    ["打断"]       = "interrupt",
    ["沉默"]       = "silence",
    ["控制"]       = "CC",
    ["晕"]         = "stun",
    ["冰"]         = "freeze",
    ["嘲讽"]       = "taunt",
    ["减速"]       = "slow",
    ["加速"]       = "speed boost",
    ["BUFF"]       = "buff",
    ["buff"]       = "buff",
    ["DEBUFF"]     = "debuff",
    ["debuff"]     = "debuff",
    ["大招"]       = "ultimate",
    ["技能"]       = "ability",
    ["冷却"]       = "cooldown",
    ["复活术"]     = "rez",
    ["灵魂石"]     = "soulstone",
    ["战斗复活"]   = "combat rez",
    ["激流"]       = "bloodlust",
    ["英勇"]       = "heroism",

    -- Loot / economy
    ["竞价"]       = "bid",
    ["拍卖"]       = "auction",
    ["银"]         = "silver",
    ["铜"]         = "copper",
    ["土豪"]       = "whale",
    ["穷"]         = "broke",
    ["史诗"]       = "epic",
    ["蓝装"]       = "blue gear",
    ["绿装"]       = "green gear",
    ["橙装"]       = "legendary",
    ["紫装"]       = "epic gear",
    ["白装"]       = "white gear",
    ["套装"]       = "set gear",
    ["武器"]       = "weapon",
    ["护甲"]       = "armor",
    ["戒指"]       = "ring",
    ["项链"]       = "necklace",
    ["背包"]       = "bag",
    ["材料"]       = "materials",
    ["药水"]       = "potion",
    ["绷带"]       = "bandage",
    ["食物"]       = "food",
    ["需要"]       = "need",
    ["贪婪"]       = "greed",
    ["传递"]       = "pass",

    -- Questing / progression
    ["主线"]       = "main quest",
    ["支线"]       = "side quest",
    ["日常"]       = "daily quest",
    ["声望"]       = "reputation",
    ["荣誉"]       = "honor",
    ["战场"]       = "battleground",
    ["PVP"]        = "PVP",
    ["PVE"]        = "PVE",
    ["技能点"]     = "talent points",
    ["等级"]       = "level",
    ["满级"]       = "max level",
    ["经验"]       = "experience",
    ["刷"]         = "grind",
    ["刷怪"]       = "grind mobs",
    ["怪"]         = "mob",
    ["精英"]       = "elite",
    ["首领"]       = "boss",
    ["地图"]       = "map",
    ["坐骑"]       = "mount",
    ["宠物"]       = "pet",
    ["技能书"]     = "skill book",

    -- Social / reactions
    ["加油"]       = "good luck",
    ["可以"]       = "okay",
    ["不行"]       = "no",
    ["真的"]       = "really",
    ["当然"]       = "of course",
    ["也许"]       = "maybe",
    ["随便"]       = "whatever",
    ["没有"]       = "no / none",
    ["有"]         = "yes / have",
    ["快点"]       = "hurry up",
    ["稳"]         = "steady",
    ["稳住"]       = "hold steady",
    ["注意"]       = "watch out",
    ["小心"]       = "be careful",
    ["行"]         = "sure",
    ["问题"]       = "problem",
    ["没问题"]     = "no problem",
    ["对"]         = "correct",
    ["错了"]       = "wrong",
    ["厉害"]       = "impressive",
    ["哈哈哈"]     = "lol",
    ["哈哈哈哈"]   = "lmao",
    ["笑死"]       = "lmao",
    ["服了"]       = "unbelievable",
    ["太难了"]     = "too hard",
    ["简单"]       = "easy",
    ["无聊"]       = "boring",
    ["好玩"]       = "fun",
    ["牛"]         = "nice",
    ["牛逼"]       = "awesome",
    ["6"]          = "nice",

    -- AFK / status
    ["在线"]       = "online",
    ["离线"]       = "offline",
    ["忙"]         = "busy",
    ["回来了"]     = "back",
    ["吃饭"]       = "eating",
    ["睡觉"]       = "sleeping",
    ["上厕所"]     = "bathroom break",

    -- Group composition
    ["满5"]        = "full 5/5",
    ["缺1"]        = "need 1 more",
    ["缺2"]        = "need 2 more",
    ["缺3"]        = "need 3 more",
    ["缺4"]        = "need 4 more",

    -- Role abbreviations
    ["T"]          = "tank",
    ["DPS位"]      = "DPS spot",
    ["法系"]       = "caster DPS",
    ["物理"]       = "melee DPS",

    -- Dungeon abbreviations
    ["ZNSY"]       = "ZA",
    ["MLTD"]       = "MARA",
    ["ZAM"]        = "ZA",
    ["ZM"]         = "ZA",

    -- Carry / lockout terms
    ["带飞"]       = "carry run",
    ["全程带"]     = "full carry",
    ["自己有本"]   = "have lockout",
    ["没本"]       = "no lockout",
    ["地下城"]     = "dungeon",
    ["本周"]       = "this week",
    ["首领击杀"]   = "boss kill",

    -- Time phrases
    ["现在开"]     = "starting now",
    ["马上开"]     = "starting soon",
    ["几点"]       = "what time?",
    ["几号开"]     = "what time starting?",

    -- GDKP / payment terms
    ["底价"]       = "minimum bid",
    ["一口价"]     = "buyout price",
    ["分钱"]       = "split gold",
    ["保底"]       = "guaranteed payout",
}


    -- Additional LFG terms
    ["北都"]       = "LBRS",
    ["南都"]       = "UBRS",
    ["任务队"]     = "quest group",
    ["来个"]       = "need a",
}